### ISSUE TITLE
An error occured during Computing the distances

### ISSUE THREAD

**Issue by sameerkhurana10** [bootphon/ABXpy#16]
Hi, 

running `python bin/prepare_eval1.py -c all`, gives me the following error

```
Traceback (most recent call last):
  File "bin/prepare_eval1.py", line 132, in <module>
fullrun(task, args.verbose)
  File "bin/prepare_eval1.py", line 99, in fullrun
t = ABXpy.task.Task(itemfilename, on, across, by, verify=False, verbose=verbose)
```

what could be going wrong?

**Comment by mmmaat** [comment]
Hi,

I need more context to understand the bug... 
* What is `bin/sample_eval1.py`, can you paste it here? 
* Are you in a Docker container (which one)? 
* Can you pass the ABXy tests (by running `python setup.py test` in the ABXpy root folder)?

**Comment by sameerkhurana10** [comment]
Hi,

Sorry, I should have mentioned that I am running Zerospeech2015 branch.

In the above branch we have `bin/sample_eval1.py`

I am not in a docker container.

Running `python setup.py test ` in branch zerospeech2015, I have attached the full log file. (4 tests failed).
[test_log.txt](https://github.com/bootphon/ABXpy/files/2931894/test_log.txt)
