### ISSUE TITLE
make test failed on branch master

### ISSUE THREAD

**Issue by sameerkhurana10** [bootphon/ABXpy#17]
hi,

created a conda python 2 environment. did `pip install cython`, `pip install git+https://github.com/bootphon/ABXpy ` and `make test`. Got the following error:

```
 /Users/sameerkhurana/repos/ABXpy/ABXpy/task.py:828: DeprecationWarning:
  .ix is deprecated. Please use
  .loc for label based indexing or
  .iloc for positional indexing

  See the documentation here:
  http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
    on_across_by_values = dict(db.ix[block[0]])

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================================================ 9 failed, 12 passed, 269 warnings in 13.61 seconds ============================================================================
Closing remaining open files:test_items/data.abx...Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/file.py", line 134, in close_all
    fileh.close()
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/file.py", line 2732, in close
    self.root._f_close()
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/group.py", line 937, in _f_close
    self._g_close_descendents()
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/group.py", line 901, in _g_close_descendents
    node_manager.close_subtree(self._v_pathname)
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/file.py", line 543, in close_subtree
    self._close_nodes(paths, cache.pop)
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/file.py", line 516, in _close_nodes
    node._g_close()
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/group.py", line 910, in _g_close
    self._g_close_group()
  File "tables/hdf5extension.pyx", line 1090, in tables.hdf5extension.Group._g_close_group
HDF5ExtError: HDF5 error back trace

  File "H5G.c", line 812, in H5Gclose
    not a group

End of HDF5 error back trace
 File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/file.py", line 134, in close_all
    fileh.close()
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/file.py", line 2732, in close
    self.root._f_close()
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/group.py", line 937, in _f_close
    self._g_close_descendents()
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/group.py", line 901, in _g_close_descendents
    node_manager.close_subtree(self._v_pathname)
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/file.py", line 543, in close_subtree
    self._close_nodes(paths, cache.pop)
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/file.py", line 516, in _close_nodes
    node._g_close()
  File "/Users/sameerkhurana/anaconda3/envs/zerospeech/lib/python2.7/site-packages/tables/group.py", line 910, in _g_close
    self._g_close_group()
  File "tables/hdf5extension.pyx", line 1090, in tables.hdf5extension.Group._g_close_group
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5G.c", line 812, in H5Gclose
    not a group

End of HDF5 error back trace

Problems closing the Group feat_dbs
make: *** [test] Error 1
```

**Comment by mmmaat** [comment]
Indeed I replicated your bug and the installation instruction was pretty outdated. I think the issue is installing h5py from pip. Please try the updated instruction at https://github.com/bootphon/ABXpy#installation

**Comment by sameerkhurana10** [comment]
thanks
