### ISSUE TITLE
error during import

### ISSUE THREAD

**Issue by sophiazhi** [bootphon/ABXpy#24]
I receive the following error when i import `ABXpy.distances.distances`:
```
Traceback (most recent call last):
  File "abxpy_eval.py", line 5, in <module>
    import ABXpy.distances.distances as dis
  File "/home/szhi/miniconda3/envs/abx_eval/lib/python3.8/site-packages/ABXpy/distances/distances.py", line 8, in <module>
    import h5features
  File "/home/szhi/.local/lib/python3.8/site-packages/h5features/__init__.py", line 31, in <module>
    from .h5features import read
  File "/home/szhi/.local/lib/python3.8/site-packages/h5features/h5features.py", line 29, in <module>
    from .data import Data
  File "/home/szhi/.local/lib/python3.8/site-packages/h5features/data.py", line 22, in <module>
    from .features import Features, SparseFeatures
  File "/home/szhi/.local/lib/python3.8/site-packages/h5features/features.py", line 21, in <module>
    import scipy.sparse as sp
  File "/home/szhi/.local/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 228, in <module>
    from .base import *
  File "/home/szhi/.local/lib/python3.8/site-packages/scipy/sparse/base.py", line 10, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/home/szhi/.local/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 16, in <module>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/home/szhi/.local/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 16, in <listcomp>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/home/szhi/miniconda3/envs/abx_eval/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'
```
It seems that the problem is caused by `'typeDict'` being deprecated by numpy after numpy version 1.21, but after downgrading numpy to 1.21 I received a different error `ImportError: numpy.core.multiarray failed to import`.  Is there an example environment (packages + exact versions) that works for abxpy, or another way I could resolve this issue?

**Comment by sophiazhi** [comment]
Resolved with `numpy=1.23.4 scipy=1.9.3 h5py=3.7.0`
